/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include <string.h>
#include <android/log.h>

#include <vector>
#include <algorithm>
#include <opencv2/opencv.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d/features2d.hpp>
/* Header for class com_vivek_dettext_MainActivity */

using namespace cv;

#ifndef _Included_com_vivek_dettext_MainActivity
#define _Included_com_vivek_dettext_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vivek_dettext_MainActivity
 * Method:    detectText
 * Signature: (Lorg/opencv/core/Mat;Lorg/opencv/core/Mat;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_vivek_dettext_MainActivity_detectText (JNIEnv *, jobject, jlong inputFrame, jlong procFrame);
Mat adaptiveDecomposition(Mat srcMat);
Mat extractMSER(Mat srcMat, double delta, double minDiversity, double maxVariation);
Mat strokeWidthTransform(Mat srcMat, int searchDirection);
void updateStrokeWidthTransform(Mat & swtMap, Mat & theta, Mat & edgeMap, vector<Point> & edgePoints, vector<Point> & strokePoints, int searchDirection, int purpose);

#ifdef __cplusplus
}
#endif
#endif
